In [1]:
import numpy as np
import pandas as pd

/Users/juhimalwade/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [9]:
# import numpy as np
students = pd.read_csv('https://raw.githubusercontent.com/kiat/Elements-of-Data-Analytics/refs/heads/main/datasets/Librarie/Students.csv')
books = pd.read_csv('https://raw.githubusercontent.com/kiat/Elements-of-Data-Analytics/refs/heads/main/datasets/Librarie/Books.csv')
borrow = pd.read_csv('https://raw.githubusercontent.com/kiat/Elements-of-Data-Analytics/refs/heads/main/datasets/Librarie/Borrow.csv')
students.head()

    SID           Name              Department  Year
0  S001       Ali Khan        Computer Science  2026
1  S002     Sara Ahmed  Electrical Engineering  2027
2  S003     John Smith  Mechanical Engineering  2028
3  S004    Emily Brown        Computer Science  2029
4  S005  Mohammed Noor     Information Systems  2026

In [3]:
books.head()

    BID                    Title        Author     Category
0  B001         Database Systems  Silberschatz   Technology
1  B002        Operating Systems     Tanenbaum   Technology
2  B003        Computer Networks        Kurose   Technology
3  B004  Artificial Intelligence       Russell   Technology
4  B005           Linear Algebra        Strang  Mathematics

In [4]:
borrow.head()

    SID   BID  BorrowDate  ReturnDate
0  S014  B087  2026-01-02         NaN
1  S022  B144  2026-01-03  2026-01-20
2  S007  B019  2026-01-04         NaN
3  S031  B156  2026-01-05  2026-01-22
4  S045  B003  2026-01-06  2026-01-24

# Query 1: List all students names and ids of Students of Year 2026.

In [10]:
students[students['Year'] == 2026][['Name', 'SID']]

              Name   SID
0         Ali Khan  S001
4    Mohammed Noor  S005
8      Omar Hassan  S009
12   Robert Miller  S013
16     James Lewis  S017
20   Ahmed Youssef  S021
24     Chris Evans  S025
28     Paul Turner  S029
32     Andrew Hill  S033
36       Tom Baker  S037
40   Steven Wright  S041
44    Henry Carter  S045
48  Mustafa Ozturk  S049

# Query 2: Find all books in the "Technology" category

In [12]:
books[books['Category'] == "Technology"][["BID", "Title", "Author"]]

     BID                       Title        Author
0   B001            Database Systems  Silberschatz
1   B002           Operating Systems     Tanenbaum
2   B003           Computer Networks        Kurose
3   B004     Artificial Intelligence       Russell
10  B011               Digital Logic          Mano
11  B012        Software Engineering   Sommerville
12  B013                 Data Mining           Han
18  B019            Machine Learning      Mitchell
19  B020                  Algorithms          CLRS
25  B026             Compiler Design           Aho
26  B027         Distributed Systems     Coulouris
27  B028                Cryptography     Stallings
33  B034  Human Computer Interaction        Preece
34  B035           Computer Graphics         Foley
40  B041       Information Retrieval       Manning
41  B042          Big Data Analytics          Marz
46  B047             Control Systems         Ogata
47  B048            Embedded Systems          Barr

# Query 3: Find names of students from the “Computer Science” department

In [15]:
students[students["Department"] == "Computer Science"]["Name"]

0          Ali Khan
3       Emily Brown
8       Omar Hassan
15     Sophia Clark
22      Brian Adams
29     Leila Haddad
36        Tom Baker
43    Layla Ibrahim
Name: Name, dtype: object

# Query 4: Find titles of all books borrowed by students

In [49]:
pd.merge(borrow, books, on ='BID', how = 'left')["Title"].drop_duplicates().dropna()

2          Machine Learning
4         Computer Networks
6     Information Retrieval
9      Discrete Mathematics
13           Modern Physics
17      Classical Mechanics
19       Physical Chemistry
23         Electromagnetics
27      Distributed Systems
29         Embedded Systems
31           Linear Algebra
35            Number Theory
39         Particle Physics
43              Data Mining
47        Operating Systems
53               Algorithms
57            Digital Logic
59           Nanotechnology
65                 Topology
69               Set Theory
71          Compiler Design
75        Organic Chemistry
77             Biochemistry
79               Biophysics
83          Fluid Mechanics
87                 Calculus
93              Game Theory
Name: Title, dtype: object

# Query 5: Find names of students who have borrowed at least one book

In [82]:
pd.merge(borrow, students, on = "SID", how = "left")["Name"].drop_duplicates().sort_values()

12      Ahmed Youssef
0        Aisha Rahman
29           Ali Khan
38         Amal Saeed
39           Anna Lee
33        Brian Adams
45        Chris Evans
37      Daniel Garcia
2        David Wilson
35        Emily Brown
25        Eric Nelson
7        Ethan Brooks
6           Farah Ali
46       George Allen
36       Hannah Green
4        Henry Carter
28     Isabella Young
17        James Lewis
3         Jason Moore
8          John Smith
42       Julia Taylor
40       Kevin Walker
1         Laura Scott
13      Layla Ibrahim
15       Leila Haddad
14     Linda Martinez
26        Maria Lopez
21    Michael Johnson
23      Mohammed Noor
20     Mustafa Ozturk
11         Nina Patel
9          Noah White
5         Omar Hassan
31        Paul Turner
44        Rania Saleh
27      Robert Miller
43      Ryan Phillips
30       Salma Farouk
41       Samir Nasser
18         Sara Ahmed
32       Sophia Clark
16      Steven Wright
10          Tom Baker
22      Victoria King
34       Yara Mansour
19        Yusuf Demir
24          Zara Khan
Name: Name, dtype: object

# Query 6: Find students who have borrowed "Technology" books

In [78]:
student_ids = pd.merge(borrow, books[books["Category"] == "Technology"], on = "BID", how = "inner")["SID"].drop_duplicates()
pd.merge(student_ids, students, on = "SID", how = "left")["Name"]

0     David Wilson
1     Henry Carter
2        Farah Ali
3    Robert Miller
4         Ali Khan
5    Ryan Phillips
6     Ethan Brooks
7      Omar Hassan
8        Tom Baker
9        Zara Khan
Name: Name, dtype: object

# Query 7: Find students who have not returned their books

In [77]:
pd.merge(borrow[borrow["ReturnDate"].isnull()], students, on = "SID", how = "left")["Name"].drop_duplicates()

0        Aisha Rahman
1        David Wilson
2         Omar Hassan
3        Ethan Brooks
4          Noah White
5          Nina Patel
6       Layla Ibrahim
7        Leila Haddad
8         James Lewis
9         Yusuf Demir
10    Michael Johnson
11      Mohammed Noor
12        Eric Nelson
13      Robert Miller
14           Ali Khan
15        Paul Turner
16        Brian Adams
17        Emily Brown
18      Daniel Garcia
19           Anna Lee
20       Samir Nasser
21      Ryan Phillips
22        Chris Evans
24        Laura Scott
25        Jason Moore
28          Tom Baker
29      Ahmed Youssef
30     Linda Martinez
31      Steven Wright
32         Sara Ahmed
33     Mustafa Ozturk
34      Victoria King
35          Zara Khan
36        Maria Lopez
37     Isabella Young
38       Salma Farouk
39       Sophia Clark
40       Yara Mansour
41       Hannah Green
42         Amal Saeed
43       Kevin Walker
44       Julia Taylor
45        Rania Saleh
46       George Allen
Name: Name, dtype: object

# Query 8: Count total number of students

In [125]:
students["SID"].nunique()

50

# Query 9: Count number of books per category

In [126]:
books["Category"].value_counts()

Category
Technology     18
Science        18
Mathematics    14
Name: count, dtype: int64

# Query 10: Find top-10 students based on borrowing count

In [95]:
pd.merge(borrow, students, on = "SID", how = "left")["Name"].value_counts().head(10)

Name
Ethan Brooks      6
Aisha Rahman      4
Emily Brown       4
Maria Lopez       4
Robert Miller     4
Isabella Young    4
Ali Khan          4
Salma Farouk      4
Paul Turner       4
Sophia Clark      4
Name: count, dtype: int64

# Query 11: Find departments sorted by total number of borrowed books

In [100]:
pd.merge(borrow, students, on = "SID", how = "left")["Department"].value_counts()

Department
Computer Science          32
Chemistry                 30
Physics                   28
Mechanical Engineering    28
Electrical Engineering    24
Information Systems       24
Mathematics               24
Name: count, dtype: int64

# Query 12: Find number of borrowers per department

In [118]:
pd.merge(borrow, students, on = "SID", how = "left").groupby("Department")["SID"].nunique()

Department
Chemistry                 7
Computer Science          8
Electrical Engineering    6
Information Systems       6
Mathematics               6
Mechanical Engineering    7
Physics                   7
Name: SID, dtype: int64

# Query 13: Find departments sorted by total number of borrowed books

In [116]:
pd.merge(borrow, students, on = "SID", how = "left")["Department"].value_counts()

Department
Computer Science          32
Chemistry                 30
Physics                   28
Mechanical Engineering    28
Electrical Engineering    24
Information Systems       24
Mathematics               24
Name: count, dtype: int64

# Query 14: Count how many times each book has been borrowed (including books never borrowed)

In [142]:
pd.merge(books, borrow, on="BID", how="outer").groupby("BID")["SID"].count()

BID
B001    0
B002    2
B003    2
B004    0
B005    2
       ..
B194    2
B196    2
B197    2
B198    2
B199    2
Name: SID, Length: 118, dtype: int64

# Query 15: Count number of borrowed books per department (including departments with zero borrows)

In [147]:
pd.merge(borrow, students, on = "SID", how = "outer").groupby("Department")["BID"].count().sort_values(ascending = False)

Department
Computer Science          32
Chemistry                 30
Mechanical Engineering    28
Physics                   28
Electrical Engineering    24
Information Systems       24
Mathematics               24
Name: BID, dtype: int64

# Query 16: Count total number of students and total number of borrows per book category

In [163]:
pd.merge(borrow, books, on = "BID", how = "outer").groupby("Category")["SID"].count()

Category
Mathematics    14
Science        20
Technology     20
Name: SID, dtype: int64

In [161]:
pd.merge(borrow, books, on="BID").groupby("Category")["SID"].agg(total_students="nunique", total_borrows="count")

             total_students  total_borrows
Category
Mathematics               7             14
Science                  10             20
Technology               10             20